### ISSUE TITLE
How do you set the environment variables and where do you set them?

### ISSUE THREAD

**Issue by Mantra159** [piyx/YoutubeSpotifyDL#11]

**Comment by dejan995** [comment]
You just copy and paste the commands provided in the Readme file.
"setx" is the utility used in Windows to set user defined variables in the system.
You will have to use PowerShell or the Command Prompt.

``setx SPOTIFY_USER_ID your_user_id``
``setx SPOTIFY_CLIENT_ID your_client_id``
``setx SPOTIFY_CLIENT_SECRET your_client_secret``
``setx SPOTIFY_REDIRECT_URI 'http://localhost:8888/callback'``

For Linux distros (For Ubuntu anyway), you can replace "setx" with "export".
Again, you will have to use the terminal.

``export SPOTIFY_USER_ID=your_user_id``
``export SPOTIFY_CLIENT_ID=your_client_id``
``export SPOTIFY_CLIENT_SECRET=your_client_secret``
``export SPOTIFY_REDIRECT_URI='http://localhost:8888/callback'``

Or if you don't want to mess with the system you can create a .env file in the same folder were the app is located and write in it like this:

``SPOTIFY_USER_ID=your_user_id``
``SPOTIFY_CLIENT_ID=your_client_id``
``SPOTIFY_CLIENT_SECRET=your_client_secret``
``SPOTIFY_REDIRECT_URI='http://localhost:8888/callback'``
