### ISSUE TITLE
There seems to be an issue with the match functions

### ISSUE THREAD

**Issue by stairsb** [piyx/YoutubeSpotifyDL#16]
I downloaded the repo and followed the steps in the README. When I try to run the program I get this error.
File "ytspdl/main.py", line 26
    match user_inputs["music_service"]:
                    ^
SyntaxError: invalid syntax

I'm not familiar with python so I'm not sure how to fix the syntax here. I ran the exact command as seen in the video.

**Comment by rajdeepdas2000** [comment]
Python ≥ 3.10 is required to support structural pattern matching (match keyword). Upgrade python version and retry to get desired results.
