### ISSUE TITLE
I need help please

### ISSUE THREAD

**Issue by Karim-Senpai** [piyx/YoutubeSpotifyDL#9]
Hello guys,
I have a question about the DL. I am not an It-technician or so but i just want to get it started and i dont know what i did wrong there. It would be really nice if you could take a look at it. 

so when i type python main.py in the terminal it just redirects me to a blank site

<img width="570" alt="help 1" src="https://user-images.githubusercontent.com/96964157/147864316-f011eec1-1883-4b36-b605-416a0757dab7.PNG">

<img width="237" alt="Thats where i get redirected to" src="https://user-images.githubusercontent.com/96964157/147864331-849dc62d-65e8-4dc7-be69-71b2666034b9.PNG">

**Comment by piyx** [comment]
Hey, make sure you have set the environment variables.
Also make sure to set the redirect uri in app dashboard settings. You can [refer](https://github.com/piyx/YoutubeSpotifyDL#setup) this link to see how to set it.
Cheers!
